import ModalContainer from "@/components/ModalContainer";
import type { Metadata } from "next";

import "@/assets/styles/global.scss";
import RootInitialize from "@/components/RootInitialize";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("layout");
  return (
    <html lang="en">
      <body>
        <div id="root">
          <RootInitialize>{children}</RootInitialize>
          <ModalContainer />
        </div>

        <div id="modal"></div>
      </body>
    </html>
  );
}
